nodejs:
  # Don't modify below here
  image: https://hmcts.azurecr.io/hmcts/civil-citizen-ui:latest
  ingressHost: 

idam-pr:
  enabled: true
  redirect_uris:
    civil-citizen-ui:
      - https:///oauth2/callback
