java:
  releaseNameOverride: ${SERVICE_NAME}
  image: ${IMAGE_NAME}
  replicas: 1
  ingressHost: ${SERVICE_FQDN}
  ingressIP: ${INGRESS_IP}
  consulIP: ${CONSUL_LB_IP}
  environment:
    TESTING_SUPPORT_ENABLED: true
    IDAM_SCHEDULED_BATCHPROCESSING_INITIALPROCESSOR: ${IMAGE_NAME}
    IDAM_SCHEDULED_BATCHPROCESSING_INITIALDELAY: 180000
    IDAM_SCHEDULED_BATCHPROCESSING_FIXEDDELAY: 360000
  devApplicationInsightsInstrumentKeyName: DUMMY_APPLICATIONINSIGHTS_DUMMYKEY
  devApplicationInsightsInstrumentKey: '00000001-0001-0001-0001-000000000001'