java:
  # Don't modify below here
  image: https://hmcts.azurecr.io/hmcts/bulk-scan-payment-processor:latest
  ingressHost: 
  devApplicationInsightsInstrumentKey: "f666440f-43c0-4abb-9c20-2ce175a374f0"
