java:
  releaseNameOverride: ${SERVICE_NAME}
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  ingressIP: ${INGRESS_IP}
  consulIP: ${CONSUL_LB_IP}
  aadIdentityName: idam
  environment:
    STRATEGIC_SERVICE_URL: https://idam-api.aat.platform.hmcts.net
    STRATEGIC_PUBLIC_URL: https://idam-web-public.aat.platform.hmcts.net