job:
  # Don't modify below here
  image: https://hmcts.azurecr.io/hmcts/am-role-assignment-batch-service:latest
  ingressHost: 
  environment:
    ROLE_ASSIGNMENT_DB_HOST: am-role-assignment-service-postgres-db-v11-{{ .Values.global.environment }}.postgres.database.azure.com
    ROLE_ASSIGNMENT_DB_USERNAME: am@am-role-assignment-service-postgres-db-v11-{{ .Values.global.environment }}