java:
  environment:
    TEST_ENDPOINTS_ENABLED: true
    SMTP_ENABLED: true
    CCD_DRY_RUN: false
  # Don't modify below here
  image: https://hmcts.azurecr.io/hmcts/ctsc-work-allocation:latest
  ingressHost: 
