nodejs:
  # Don't modify below here
  image: https://hmcts.azurecr.io/hmcts/pip-frontend:latest
  ingressHost: 
  environment:
    DATA_MANAGEMENT_URL: https://pip-data-management.staging.platform.hmcts.net
