nodejs:
  # Don't modify below here
  image: https://hmcts.azurecr.io/hmcts/fact-admin:latest
  ingressHost: 
  environment:
    OAUTH_CLIENT_REDIRECT: https:///oauth2/callback
    FRONTEND_URL: "https://fact.{{ .Values.global.environment }}.platform.hmcts.net"
idam-pr:
  enabled: false
  redirect_uris:
    FACT Admin:
      - https:///oauth2/callback
