apiVersion: v2
name: ethos-ecm-consumer
home: https://github.com/hmcts/ecm-consumer
version: 0.1.3
description: HMCTS ECM Consumer Updates Queue Service
maintainers:
  - name: HMCTS ETHOS Team
    email: javier.carretero@hmcts.net
dependencies:
  - name: java
    version: ~3.0.0-beta
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
