java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    ECM_CONSUMER_DB_CONN_OPTIONS: ""
    ECM_CONSUMER_POSTGRES_HOST: "{{ .Release.Name }}-postgresql"
    ECM_CONSUMER_POSTGRES_DATABASE: "{{ .Values.postgresql.postgresqlDatabase}}"
    ECM_CONSUMER_POSTGRES_USER: "{{ .Values.postgresql.postgresqlUsername}}"
    ECM_CONSUMER_POSTGRES_PASSWORD: "{{ .Values.postgresql.postgresqlPassword}}"
  keyVaults:
    ethos-shared:
      resourceGroup: ethos
      secrets:
        - ecm-consumer-s2s-key
        - caseworker-user-name
        - caseworker-password
        - gov-notify-api-key
        - create-updates-queue-send-connection-string
        - create-updates-queue-listen-connection-string
        - update-case-queue-send-connection-string
        - update-case-queue-listen-connection-string
        - idam-client-secret
  postgresql:
    enabled: true
