apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-keyclock-realm-cm
data:
{{ (.Files.Glob "keycloak/master-realm.json").AsConfig | indent 2 }}
{{ (.Files.Glob "keycloak/jhipster-realm.json").AsConfig | indent 2 }}
