java:
  image: https://hmcts.azurecr.io/hmcts/ccd-message-publisher:latest
  ingressHost: 
  environment:
    DATA_STORE_DB_NAME: ccd_data_store
    DATA_STORE_DB_HOST: ccd-data-store-api-postgres-db-v11-aat.postgres.database.azure.com
  keyVaults:
    ccd:
      secrets:
        - data-store-api-POSTGRES-USER-V11
        - data-store-api-POSTGRES-PASS-V11
        - ccd-servicebus-connection-string
        - AppInsightsInstrumentationKey
