nodejs:
  image: https://hmcts.azurecr.io/hmcts/sscs-cor-frontend:latest
  ingressHost: 
  environment:
    NODE_ENV: preprod
    MYA_FEATURE_FLAG: "true"
    ADDITIONAL_EVIDENCE_FEATURE_FLAG: "true"
    EVIDENCE_UPLOAD_QUESTION_PAGE_ENABLED: "false"
    EVIDENCE_UPLOAD_QUESTION_PAGE_OVERRIDE_ALLOWED: "true"
