java:
  # Don't modify below here
  image: https://hmcts.azurecr.io/hmcts/rpe-send-letter-service:latest
  ingressHost: 
  devApplicationInsightsInstrumentKey: "71df5a0f-ebbe-445c-b1d1-d10d349f0970"
  environment:
    FLYWAY_NOOP_STRATEGY: "false"
