job:
  # Don't modify below here
  image: https://hmcts.azurecr.io/hmcts/am-role-assignment-refresh-batch:latest
  ingressHost: 
  environment:
    ORG_ROLE_MAPPING_DB_HOST: am-org-role-mapping-service-postgres-db-v11-{{ .Values.global.environment }}.postgres.database.azure.com
    ORG_ROLE_MAPPING_DB_USERNAME: am@am-org-role-mapping-service-postgres-db-v11-{{ .Values.global.environment }}