
nodejs:
  # Don't modify below here
  image: https://hmcts.azurecr.io/hmcts/nfdiv-frontend:latest
  ingressHost: 
  registerAdditionalDns:
    enabled: true
    prefix: civil
    primaryIngressHost: 
  environment:
    OAUTH_CLIENT_REDIRECT: https:///oauth2/callback

idam-pr:
  enabled: false
  redirect_uris:
    divorce:
      - https:///oauth2/callback
      - https://civil-/oauth2/callback
