nodejs:
  # Don't modify below here
  image: https://hmcts.azurecr.io/hmcts/nfdiv-frontend:latest
  ingressHost: 
  devmemoryRequests: '256Mi'
  registerAdditionalDns:
    enabled: true
    prefix: civil
    primaryIngressHost: 
  environment:
    OAUTH_CLIENT_REDIRECT: https:///oauth2/callback

idam-pr:
  enabled: false
