nodejs:
  # Don't modify below here
  image: https://hmcts.azurecr.io/hmcts/nfdiv-frontend:latest
  ingressHost: 
  devmemoryLimits: '2Gi'
  devcpuLimits: '1000m'
  devmemoryRequests: '512Mi'
  devcpuRequests: '500m'
  registerAdditionalDns:
    enabled: true
    prefix: civil
    primaryIngressHost: 
  environment:
    OAUTH_CLIENT_REDIRECT: https:///oauth2/callback

idam-pr:
  enabled: false
