# Don't modify this file, it is only needed for the pipeline to set the image and ingressHost
java:
  environment:
    DB_ALLOW_DELETE_RECORD: "true"
  image: https://hmcts.azurecr.io/hmcts/lau-case-backend:latest
  ingressHost: 
