java:
  # Don't modify below here
  image: https://hmcts.azurecr.io/hmcts/em-stitching:latest
  ingressHost: 
  environment:
    RUN_DB_MIGRATION_ON_STARTUP: 'false'
    TASK_ENV: documentTaskLock-aat-staging
