java:
  # Don't modify below here
  image: https://hmcts.azurecr.io/hmcts/am-judicial-booking-service:latest
  ingressHost: 
  keyVaults:
    am:
      secrets:
        - am-judicial-booking-service-s2s-secret
        - judicial-booking-service-POSTGRES-PASS
        - AppInsightsInstrumentationKey

